server:
  port: 8090
spring:
  shardingsphere:
    datasource:
      names: master,slave
      # \u4E3B\u6570\u636E\u6E90
      master:
        driver-class-name: com.mysql.jdbc.Driver
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://120.78.206.144:3306/ds_1?characterEncoding=utf-8
        username: root
      # \u4ECE\u6570\u636E\u6E90
      slave:
        driver-class-name: com.mysql.jdbc.Driver
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://120.78.206.144:3306/ds_2?characterEncoding=utf-8
        username: root
    # \u8BFB\u5199\u5206\u79BB\u914D\u7F6E
    masterslave:
      load-balance-algorithm-type: round_robin
      master-data-source-name: master
      name: dataSource
      slave-data-source-names: slave
    # \u663E\u793Asql
    props:
      sql:
        show: true

